from setuptools import setup, Extension
from Cython.Distutils import build_ext

def main(cythonize=True):
    ext_modules = [
        Extension('sbf_parser.sbf', ['sbf_parser/sbf.pyx', 'sbf_parser/c_crc.c']),
        Extension('sbf_parser.blocks', ['sbf_parser/blocks.py']),
        Extension('sbf_parser.parsers', ['sbf_parser/parsers.pyx'])
    ]
    
    for e in ext_modules:
    	e.cython_directives = {'language_level': "3"}

    setup(name='sbf_parser',
          version='1.0',
          description='A Python module (in C) to parse SBF stream generated by Septentrio receivers.',
          author='Jashandeep Sohi, Marco Job, Méven Jeanne-Rose',
          author_email='jashandeep.s.sohi@gmail.com, marco.job@bluewin.ch, meven.j.r@gmail.com',
          url='https://github.com/MJeanneRose/',
          packages = ['sbf_parser'],
          cmdclass = {'build_ext': build_ext},
          ext_modules = ext_modules
    )

if __name__ == '__main__':
    main()
